variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

stages:
  - build
  - test
  - sonarqube-check
  - deploy
build:
  stage: build
  script:
  - ./gradlew assemble

test:
  stage: test
  script:
  - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  image: gradle:8.6-jdk17-jammy
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonar
  allow_failure: true
  only:
    - main
    - develop
    - /^feature\/.*$/
    
deploy:
    stage: deploy
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker build -t my-backend:latest .
      - docker-compose -f docker-compose.yml up -d --build
    only:
      - main
      - develop
      - /^feature\/.*$/