variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  FRONTEND_REPO: "https://git.fhict.nl/I500157/individual-assignment-semester-3-fe.git"
  FRONTEND_REPO_USER: "gitlab+deploy-token-398"
  FRONTEND_REPO_TOKEN: "dvPr17fePz2kybw-JT8Y"

stages:
  - build
  - test
  - sonarqube-check

build:
  stage: build
  script:
    - git clone https://${FRONTEND_REPO_USER}:${FRONTEND_REPO_TOKEN}@${FRONTEND_REPO} ../frontend
    - ./gradlew assemble
    - docker build -t my-backend:latest -f Dockerfile .
    - cd ../frontend/individual-assignment-semester-3-fe
    - docker build -t my-frontend:latest -f Dockerfile .

test:
  stage: test
  script:
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  image: gradle:8.6-jdk17-jammy
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonar
  allow_failure: true
  only:
    - main
    - develop
    - /^feature\/.*$/

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
  only:
    - main
    - develop
    - /^feature\/.*$/