variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  FRONTEND_REPO: "git.fhict.nl/I500157/individual-assignment-semester-3-fe.git"
  FRONTEND_REPO_USER: "gitlab+deploy-token-398"
  FRONTEND_REPO_TOKEN: "dvPr17fePz2kybw-JT8Y"

stages:
  - build
  - test
  - sonarqube-check
  - deploy
build:
  stage: build
  script:
  - ./gradlew assemble

test:
  stage: test
  script:
  - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  image: gradle:8.6-jdk17-jammy
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonar
  allow_failure: true
  only:
    - main
    - develop
    - /^feature\/.*$/

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - if [ -d "../frontend" ]; then rm -rf ../frontend; fi
    - git clone https://${FRONTEND_REPO_USER}:${FRONTEND_REPO_TOKEN}@${FRONTEND_REPO} ../frontend
  script:
    - ./gradlew assemble

    - docker build -t my-backend:latest -f Dockerfile .

    - cd ../frontend/individual-assignment-semester-3-fe
    - docker build -t my-frontend:latest -f Dockerfile .

    - cd ${CI_PROJECT_DIR}
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - main
    - develop
    - /^feature\/.*$/