version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
    depends_on:
      - gamehub-staging-db
    networks:
      - gamehub-network

  frontend:
    build:
      context: ../frontend/individual-assignment-semester-3-fe
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - gamehub-network

  gamehub-staging-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gamehub_staging_db
    ports:
      - "3369:3306"
    networks:
      - gamehub-network
    volumes:
      - gamehub-db-data:/var/lib/mysql

networks:
  gamehub-network:
    external: true

volumes:
  gamehub-db-data: