@startuml GameHub-Container
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

left to right direction

System_Boundary(gamehub, "GameHub") {
    Container(webApp, "Web Application", "React", "Allows users to interact with the GameHub platform.")
    Container(backendService, "Backend Service", "Spring Boot", "Handles business logic and data processing.")
    ContainerDb(database, "Database", "MySQL", "Stores all the platform's data.")
}

Person(player, "Player", "A user who plays games and uses GameHub to find and discuss games.")
Person(gameDeveloper, "Game Developer", "A user who develops games and uses GameHub to showcase and discuss their games.")

Rel(player, webApp, "Uses")
Rel(gameDeveloper, webApp, "Uses")
Rel(webApp, backendService, "Sends API requests to")
Rel(backendService, database, "Reads from and writes to")


@enduml